services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      STORAGE_TYPE: ${STORAGE_TYPE:-}
      STORAGE_HOST: ${STORAGE_HOST:-}
      STORAGE_NAME: ${STORAGE_NAME:-}
      STORAGE_COLLECTION: ${STORAGE_COLLECTION:-}
    volumes:
      - ./data/:/data/
    depends_on:
      - mongo
    command: ["uvicorn", "app.api.endpoints:app", "--host", "0.0.0.0", "--port", "8000"]

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      STORAGE_TYPE: ${STORAGE_TYPE:-MongoDB}
      STORAGE_NAME: ${STORAGE_NAME:-form_storage}
      STORAGE_COLLECTION: ${STORAGE_COLLECTION:-forms}
    volumes:
      - mongo_data:/data/db
      - ./data/forms_mongo.json:/data/data.json
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    entrypoint: ["/docker-entrypoint-initdb.d/entrypoint.sh"]


volumes:
  mongo_data:
